net: wireguard: Comment out a function redeclaration
In file included from <built-in>:2:
/home/taalojarvi/android_kernel_xiaomi_surya/net/wireguard/compat/compat.h:843:20: error: redefinition of 'skb_mark_not_on_list'
static inline void skb_mark_not_on_list(struct sk_buff *skb)
                   ^
/home/taalojarvi/android_kernel_xiaomi_surya/include/linux/skbuff.h:1346:20: note: previous definition is here
static inline void skb_mark_not_on_list(struct sk_buff *skb)
                   ^
1 error generated.

Caused by https://github.com/Stratosphere-Kernel/android_kernel_xiaomi_surya/commit/5ac7d62e11cdf44e8b304f3a207e2a915e9674e7 since we are not upstreamed yet.
Signed-off-by: taalojarvi <sreedevan05@gmail.com>